In [1]:
#Test to open csv files and convert them into the right shape

In [2]:
import numpy as np
import pandas as pd

In [3]:
data_tweets = pd.read_csv('tweets_data_0121_0205.csv')

In [4]:
print(data.head())

   Unnamed: 0        Date  Positives  Negatives  Neutrals
0           0  2022/01/21         25         11        45
1           1  2022/01/22         25         16        69
2           2  2022/01/23         16         14        87
3           3  2022/01/24         44         21       135
4           4  2022/01/25         43         15       132


In [5]:
pos = np.array(data_tweets['Positives'])
neg = np.array(data_tweets['Negatives'])
neu = np.array(data_tweets['Neutrals'])

array([11, 16, 14, 21, 15, 23, 12,  7,  7,  5,  5, 12,  7,  6, 13,  6],
      dtype=int64)

In [16]:
tweets_array=np.array([])
for i in range(len(pos)):
    tweets_array = np.append(tweets_array , pos[i])
    tweets_array = np.append(tweets_array , neg[i])
    tweets_array = np.append(tweets_array , neu[i])
    

tweets_array = tweets_array.reshape((-1,3))
tweets_array = tweets_array.astype(int)
tweets_array

array([[ 25,  11,  45],
       [ 25,  16,  69],
       [ 16,  14,  87],
       [ 44,  21, 135],
       [ 43,  15, 132],
       [ 40,  23, 111],
       [ 37,  12,  81],
       [ 10,   7,  20],
       [  9,   7,  23],
       [  9,   5,  29],
       [ 11,   5,  25],
       [ 16,  12,  25],
       [ 16,   7,  37],
       [ 12,   6,  31],
       [ 11,  13,  37],
       [ 10,   6,  25]])

2.0

array([2, 2, 2, 0])