In [1]:
import numpy as np
import seaborn as sns
sns.set_theme(style="darkgrid")
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
#for polynomial eq import the below statement
from sklearn.preprocessing import PolynomialFeatures
from numpy import mean
from numpy import std
from numpy import cov
from scipy.stats import pearsonr

In [2]:
data_tweets = pd.read_csv('tweets_data_0121_0205.csv')
pos = np.array(data_tweets['Positives'])
neg = np.array(data_tweets['Negatives'])
neu = np.array(data_tweets['Neutrals'])
senti=np.array([])
for i in range(len(pos)):
    senti = np.append(senti , pos[i])
    senti = np.append(senti , neg[i])
    senti = np.append(senti , neu[i])
    
senti = senti.reshape((-1,3))
senti = senti.astype(int)
senti

array([[ 25,  11,  45],
       [ 25,  16,  69],
       [ 16,  14,  87],
       [ 44,  21, 135],
       [ 43,  15, 132],
       [ 40,  23, 111],
       [ 37,  12,  81],
       [ 10,   7,  20],
       [  9,   7,  23],
       [  9,   5,  29],
       [ 11,   5,  25],
       [ 16,  12,  25],
       [ 16,   7,  37],
       [ 12,   6,  31],
       [ 11,  13,  37],
       [ 10,   6,  25]])

In [3]:
data_stocks = pd.read_csv('BP.csv')
stock = data_stocks.drop(columns=['Date'])
stock=stock.to_numpy()
stock

array([[3.08500e+01, 3.10800e+01, 3.05500e+01, 3.07100e+01, 1.74726e+07],
       [2.94000e+01, 2.99900e+01, 2.88900e+01, 2.99800e+01, 2.09937e+07],
       [3.02500e+01, 3.14800e+01, 2.98500e+01, 3.14000e+01, 1.76550e+07],
       [3.20100e+01, 3.21300e+01, 3.12400e+01, 3.15000e+01, 1.66200e+07],
       [3.20200e+01, 3.21500e+01, 3.11400e+01, 3.15300e+01, 1.46987e+07],
       [3.10500e+01, 3.13500e+01, 3.06500e+01, 3.10700e+01, 1.46092e+07],
       [3.11200e+01, 3.11400e+01, 3.07500e+01, 3.09200e+01, 1.01790e+07],
       [3.12000e+01, 3.18900e+01, 3.10700e+01, 3.17600e+01, 1.54091e+07],
       [3.18000e+01, 3.20300e+01, 3.16200e+01, 3.19600e+01, 1.17752e+07],
       [3.20700e+01, 3.23400e+01, 3.16800e+01, 3.21500e+01, 1.31731e+07],
       [3.27200e+01, 3.31900e+01, 3.26900e+01, 3.28800e+01, 1.69326e+07]])

In [4]:
np.set_printoptions(suppress=False)

In [5]:
senti[3]=(senti[3]+senti[1]+senti[2])/3
senti[10]=(senti[10]+senti[8]+senti[9])/3

senti=np.delete(senti, 1,0)
senti=np.delete(senti, 1,0)
senti=np.delete(senti, 6,0)
senti=np.delete(senti, 6,0)
senti=np.delete(senti, 11,0)


print(senti)
print('-----------------')
print(stock)
print('-----------------')
print("Sentiment length: " , len(senti))
print("Stock length: " , len(stock))

[[ 25  11  45]
 [ 28  17  97]
 [ 43  15 132]
 [ 40  23 111]
 [ 37  12  81]
 [ 10   7  20]
 [  9   5  25]
 [ 16  12  25]
 [ 16   7  37]
 [ 12   6  31]
 [ 11  13  37]]
-----------------
[[3.08500e+01 3.10800e+01 3.05500e+01 3.07100e+01 1.74726e+07]
 [2.94000e+01 2.99900e+01 2.88900e+01 2.99800e+01 2.09937e+07]
 [3.02500e+01 3.14800e+01 2.98500e+01 3.14000e+01 1.76550e+07]
 [3.20100e+01 3.21300e+01 3.12400e+01 3.15000e+01 1.66200e+07]
 [3.20200e+01 3.21500e+01 3.11400e+01 3.15300e+01 1.46987e+07]
 [3.10500e+01 3.13500e+01 3.06500e+01 3.10700e+01 1.46092e+07]
 [3.11200e+01 3.11400e+01 3.07500e+01 3.09200e+01 1.01790e+07]
 [3.12000e+01 3.18900e+01 3.10700e+01 3.17600e+01 1.54091e+07]
 [3.18000e+01 3.20300e+01 3.16200e+01 3.19600e+01 1.17752e+07]
 [3.20700e+01 3.23400e+01 3.16800e+01 3.21500e+01 1.31731e+07]
 [3.27200e+01 3.31900e+01 3.26900e+01 3.28800e+01 1.69326e+07]]
-----------------
Sentiment length:  11
Stock length:  11


In [7]:
#relative mood of stock : (pos-neg)/total
rel = (senti[:,0]-senti[:,1])/senti.sum(axis=1) #(senti[:,0]+senti[:,1]+senti[:,2])
print(rel)
h1 = np.insert(senti,3,rel,axis=1)
#senti = np.delete(senti,3,axis=1)
print(h1)

[ 0.17283951  0.07746479  0.14736842  0.09770115  0.19230769  0.08108108
  0.1025641   0.0754717   0.15        0.12244898 -0.03278689]
[[ 25  11  45   0]
 [ 28  17  97   0]
 [ 43  15 132   0]
 [ 40  23 111   0]
 [ 37  12  81   0]
 [ 10   7  20   0]
 [  9   5  25   0]
 [ 16  12  25   0]
 [ 16   7  37   0]
 [ 12   6  31   0]
 [ 11  13  37   0]]


array([[ 25,  11,  45],
       [ 28,  17,  97],
       [ 43,  15, 132],
       [ 40,  23, 111],
       [ 37,  12,  81],
       [ 10,   7,  20],
       [  9,   5,  25],
       [ 16,  12,  25],
       [ 16,   7,  37],
       [ 12,   6,  31],
       [ 11,  13,  37]])