In [30]:
import numpy as np
from sklearn.linear_model import LinearRegression
#for polynomial eq import the below statement
from sklearn.preprocessing import PolynomialFeatures

In [6]:
x = np.arange(5,60,10).reshape((-1,1))
y = np.array([5, 20, 14, 32, 22, 38])

In [7]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [ ]:
np.reshape((-1,6))

In [8]:
y

array([ 5, 20, 14, 32, 22, 38])

In [9]:
model = LinearRegression()

In [10]:
model.fit(x,y)

LinearRegression()

you can directly use model = LinearRegression.fit(x,y)

In [11]:
rsq = model.score(x,y)
print('Rsquare is',rsq)
print('Intercept is',model.intercept_)
print('Slope is',model.coef_)

Rsquare is 0.715875613747954
Intercept is 5.633333333333333
Slope is [0.54]


In [1]:
#plot a graph with seaborn

In [12]:
y_pred = model.predict(x)
print('predicted response:',y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [13]:
x_new = np.arange(5).reshape((-1, 1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [14]:
y_new = model.predict(x_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]


earlier we did linear regression for one variable

now below we do multiple var linear regression

In [15]:
a = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
b = [4, 5, 20, 14, 32, 22, 38, 43]
a, b = np.array(a), np.array(b)

In [18]:
a

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [19]:
b

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [20]:
model1 = LinearRegression().fit(a,b)

In [21]:
rsq1 = model1.score(a,b)
print('Coeff of covar:',rsq1)
print('Intercept:',model1.intercept_)
print('Slope:',model1.coef_)

Coeff of covar: 0.8615939258756776
Intercept: 5.52257927519819
Slope: [0.44706965 0.25502548]


In [24]:
b_pred = model1.predict(a)
print('predicted response:', b_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [27]:
a_new = np.arange(10).reshape((-1,2))
print(a_new)
b_new = model1.predict(a_new)
print(b_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]


here we completed multi variable linear regression, like f(x,y) = ax+by+c

now we will do polynomial regression

In [34]:
c = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
d = np.array([15, 11, 2, 8, 25, 32])
#this reshape in c is done to convert the data into two dimensional from 1D. See below that data has transformed
#from 1D linear array to 2D array, with every point on a single line (array)

In [32]:
print(c)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [33]:
print(d)

[15 11  2  8 25 32]


In [35]:
transformer = PolynomialFeatures(degree=2,include_bias=False)

In [37]:
transformer.fit(c)

PolynomialFeatures(include_bias=False)

In [38]:
c_ = transformer.transform(c)

In [39]:
# or you can also write c_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(c)

In [40]:
print(c_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [41]:
model2 = LinearRegression().fit(c_,d)

In [42]:
rsq2 = model2.score(c_,d)
print('Coeff of covar:',rsq2)
print('Slope:',model2.coef_)
print('Intercept:',model2.intercept_)

Coeff of covar: 0.8908516262498564
Slope: [-1.32357143  0.02839286]
Intercept: 21.37232142857143


In [44]:
c_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(c)

In [45]:
print(c_)

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


In [46]:
model2 = LinearRegression(fit_intercept=False).fit(c_,d)

In [48]:
rsq2 = model2.score(c_,d)
print('Coeff of covar:',rsq2)
print('Slope:',model2.coef_)
print('Intercept:',model2.intercept_)

Coeff of covar: 0.8908516262498563
Slope: [21.37232143 -1.32357143  0.02839286]
Intercept: 0.0


In [51]:
d_pred = model2.predict(c_)
print('predicted response:', d_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
